swagger: '2.0'
info:
  version: 1.0.0
  title: Student Server

consumes:
  - application/json
produces:
  - application/json

paths:
  /student:
    get:
      tags:
        - student
      produces:
        - text/plain
      parameters:
        - name: id
          required: true
          type: integer
          format: int64
          in: query
          description: ID to get student information
      operationId: GetStudent
      responses:
        200:
          description: returns a Student Information
          schema:
            type: string
            description: contains a Student Informations
    post:
      tags:
        - student
      operationId: PostStudent
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/student"
      responses:
        200:
          description: contains a Student Informations
          schema:
            type: string
            description: contains a Student Informations

  /{id}:
    parameters:
      - type: integer
        format: int64
        name: id
        in: path
        required: true
    put:
      tags:
        - student
      operationId: PutStudent
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/student'
      responses:
        200:
          description: returns a Student Informations
          schema:
            type: string
            description: contains a Student Informations

    delete:
      tags:
        - student
      operationId: DeleteStudent
      responses:
        204:
          description: Delete a Student Informations
          schema:
            type: string
            description: Delete a Student Informations

  /studentlist:
    get:
      tags:
        - student
      produces:
        - text/plain
      operationId: GetStudentList
      responses:
        200:
          description: returns list of Student
          schema:
            type: string
            description: contains list of Student


definitions:
  student:
    type: object
    required:
      - name
      - department
      - enrollment
      - age
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      enrollment:
        type: integer
        format: int64
      name:
        type: string
        minLength: 1
      age:
        type: integer
        format: int32
      department:
        type: string
        minLength: 1







