swagger: '2.0'
info:
  version: 1.0.0
  title: Student Server
paths:
  /student:
    get:
      produces:
        - text/plain
      parameters:
        - name: name
          required: false
          type: string
          in: query
          description: defaults to Adil if not given
        - name: Department
          required: false
          type: string
          in: query
          description: defaults to CS if not given
        - name: age
          type: integer
          format:  int32
          in: query
          required: false
          description: Should be greater than 20
        - name: enrollment
          type: integer
          format: int64
          in: query
          required: false
          description: It is int64
      operationId: GetStudent
      responses:
        200:
          description: returns a Student Information
          schema:
            type: string
            description: contains a Student Informations
    post:
      produces:
        - text/plain
      parameters:
        - name: name
          required: false
          type: string
          in: query
          description: defaults to Adil if not given
        - name: Department
          required: false
          type: string
          in: query
          description: defaults to CS if not given
        - name: age
          type: integer
          format:  int32
          in: query
          required: false
          description: Should be greater than 20
        - name: enrollment
          type: integer
          format: int64
          in: query
          required: false
          description: It is int64
      operationId: PostStudent
      responses:
        200:
          description: returns a Student Informations
          schema:
            type: string
            description: contains a Student Informations

    put:
      produces:
        - text/plain
      parameters:
        - name: name
          required: false
          type: string
          in: query
          description: defaults to Adil if not given
        - name: Department
          required: false
          type: string
          in: query
          description: defaults to CS if not given
        - name: age
          type: integer
          format:  int32
          in: query
          required: false
          description: Should be greater than 20
        - name: enrollment
          type: integer
          format: int64
          in: query
          required: false
          description: It is int64
      operationId: PutStudent
      responses:
        200:
          description: returns a Student Informations
          schema:
            type: string
            description: contains a Student Informations

    delete:
      produces:
        - text/plain
      parameters:
        - name: Id
          required: false
          type: string
          in: query
          description: Add Id
      operationId: DeleteStudent
      responses:
        200:
          description: returns a Student Informations
          schema:
            type: string
            description: contains a Student Informations